Change poverty status threshold
PIP-Technical-Team/wbpip pull request #159
Opened 2021-07-27 14:54 UTC by tonyfujs

* Switch < to <=
* remove unused line of code

2021-07-27 14:55 UTC, tonyfujs commented
Fixes issue #158

2021-07-27 14:57 UTC, tonyfujs commented
Hey @randrescastaneda 
Can you take a look at what I did here when you get a chance? This is a very small code change, but I want to make sure it makes sense from a methodology standpoint:

- It fixes the problem identified in issue #158 
- It did not break any of our existing unit tests
Thanks!

2021-08-02 15:25 UTC, randrescastaneda requested changes
Hi @tonyfujs, 
Just a very small change needs to be made. Remove the = sign from the <= expression. 
Thanks. 
Best,

2021-08-02 15:25 UTC, randrescastaneda commented on R/md_compute_poverty_stats.R
> -  alpha             <- c(0, 1, 2)
This is OK

2021-08-02 15:25 UTC, randrescastaneda commented on R/md_compute_poverty_stats.R
> +  pov_status        <- (welfare <= povline_lcu)
Poverty status should be one if welfare is less than the poverty lines, not less or equal to... 
![image](https://user-images.githubusercontent.com/35301997/127885450-2bb0d426-2634-4409-b060-f46ebca47408.png)

2021-08-02 15:28 UTC, randrescastaneda commented
Hi @tonyfujs, 
I requested some changes but I did them myself, you don't need to do anything. I'll merge.

2021-08-02 15:28 UTC, merged