vectorize spl
PIP-Technical-Team/wbpip pull request #216
Opened 2022-12-14 20:48 UTC by randrescastaneda

2023-02-10 21:35 UTC, randrescastaneda commented
Hi @tonyfujs , 

Whenever you have a chance, could could you please merge this PR. I need it to estimate the SPL in the pipeline. 

Thank you.

2023-02-13 11:56 UTC, tonyfujs requested changes

2023-02-13 11:56 UTC, tonyfujs commented on R/compute_spl.R
> +  threshold_rate <-  0.5
Why did you move it to the function body (instead of leaving it as a function argument)?

2023-02-13 11:56 UTC, tonyfujs commented on R/compute_spl.R
> +  }
As discussed on the phone. Let's keep `wbpip` a relatively low-level package to power the API and an upcoming higher-level package for end-users to use directly. `cli` interactive message will be there in this interactive package.

2023-02-13 11:56 UTC, tonyfujs commented on R/compute_spl.R
> +    min_level <- 2.15
I'm not sure this should be ahrd-coded in the function's body... This should probably be either function arguments that take their value when being called from higher level function...

2023-02-13 16:00 UTC, randrescastaneda commented
I'll make the PR to DEV

2023-02-14 08:44 UTC, merged