Refactor consistency
PIP-Technical-Team/wbpip pull request #236
Opened 2024-01-23 20:09 UTC by zander-prinsloo

Specific points:
1. export functions
2. clean and reformat some code
3.  `gd_lq_key_values` - new function, used in places such as `gd_estimate_dist_stats`
4.  check small argument modifications on `gd_compute_pov_*_lb` functions
5. review `gd_compute_poverty_stats_lq_replacement.R` and all associated functions
6. Review `md_compute_poverty_stats_replacement.R` and all associated functions
7. Many changes in `gd_utils.R`
8.  All new functions are tested
9. A vignette added

2024-01-24 15:01 UTC, randrescastaneda commented
Task linked: [CU-86869wcrp {wbpip} maintenance](https://app.clickup.com/t/86869wcrp)

2024-01-24 15:01 UTC, randrescastaneda commented
Task linked: [CU-8686teb15 refactor for consistency](https://app.clickup.com/t/8686teb15)

2024-01-24 18:22 UTC, randrescastaneda requested changes
I have added several changes

2024-01-24 18:22 UTC, randrescastaneda commented on R/gd_compute_poverty_stats_lq_replacement.R
> +    gp <- 2 * (1 + (((mean / povline) - 1) * pov_gap / pov_gap_sq))
All of these calculations should be converted to functions. This is not urgent and should NOT be done for this PR, but should be done for the next one

2024-01-24 19:10 UTC, randrescastaneda commented
Hi @tonyfujs, 

Even though this PR includes many changes, none affect the regular behavior of `wbpip`. As you can see below, all tests, including several new ones, are passing. The main purposes of these changes are: 

1. Expose several functions that we need in the `pipster` package
2. improve the behavior of `md_compute_poverty_stats()` and `gd_compute_poverty_stats_lq()` to allow vectorization (not fully completed yet), and allow flexibility for additional functions. Also, we created several subfunctions to be used inside these two and, more importantly, to be used independently from them. That is, the user can call the new subfunctions (e.g., `md_compute_headcount') without having to call `md_compute_poverty_stats`. Since these new subfunctions are exposed, some checks are needed and some efficiency is lost. I tested the performance of the new and old `md` and `gd` functions and the difference is negligible. For md I used 20 Million obs and you can see that though the new function is a little slower, the difference in milliseconds is irrelevant.
3. we added more examples.
4. Small changes (see initial comment by Zander in this PR)
5. we vectorized some functions. In the next PR, we will vectorize more functions. 

Please, let me know if you have any question. 

## test pass
![image](https://github.com/PIP-Technical-Team/wbpip/assets/35301997/92182a6d-6ed0-497f-b0c5-b418cf14face)

## performance comparison

### `md_compute_poverty_stats()` 20M obs
![image](https://github.com/PIP-Technical-Team/wbpip/assets/35301997/f262bfea-bfee-4ea2-a829-0a03ee1be53e)

### `gd_compute_poverty_stats_lq()`

![image](https://github.com/PIP-Technical-Team/wbpip/assets/35301997/fb23868e-8233-4d9d-a5eb-1bb3eb024ff1)

2024-01-24 19:10 UTC, randrescastaneda submitted a review, later dismissed

2024-01-26 16:04 UTC, tonyfujs requested changes
Hello - I have not done a full review, but made some comments. Please take a look, and let me know what you think. Thanks!

2024-01-26 16:04 UTC, tonyfujs commented on DESCRIPTION
> +    PIP-technical-team/pipload@new_pipeline
The `wbpip` package should not have any dependency on `pipload`. `pipload` is a purely internal package.

2024-01-26 16:04 UTC, tonyfujs commented on R/gd_compute_pip_stats_lb.R
> +  pov_gap <- gd_compute_pov_gap_lb( mean,  povline, headcount, A, B, C)
Not sure I'm following what is happening here... I see that the `gd_compute_pov_gap_lb` function has now gained an additional argument `u`, which defaults to `NULL`. But in these two lines of code, `u` is computed on line 442, but not passed to the  `gd_compute_pov_gap_lb` function. So either:
- It should be passed, or
- Line 442 should be deleted

Or am I missing something?

2024-01-26 16:04 UTC, tonyfujs commented on R/gd_compute_pip_stats_lb.R
> +  )
Same comment as above

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_bins.R
> +    return(dt[, bins])
Any reason for removing the quotes? As a rule of thumb, it is almost always faster to select using quoting names.

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +) {
Shouldn't this function be called `md_compute_poverty_stats_replacement` as mentioned in the roxygen chunk above? 

Okay, I think I understand what happened. The function names have been switched. `md_compute_poverty_stats` is actually the re-factored function. Then the roxygen chunk should be updated.

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +  weight_total      <- fsum(weight)
`collapse::fsum`?

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +    )
This is a low level package meant to support poverty computations in the PIP API. I believe the `pipster` package will also rely on `wbpip` to provide higher level functions that end-users can call directly. I think those checks and `cli` messages should be placed in those higher level functions, not here.

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +    weight_total      <- fsum(weight)
`collapse::fsum`

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +  povgap <- fsum(relative_distance * weight_pov) / weight_total
`collapse::fsum`

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +  }
Same comments as above above checks and `cli` messages. This function is not meant to be called directly by end-users.

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +  povsev <- fsum(relative_distance^2 * weight_pov) / weight_total
`collapse::fsum`

2024-01-26 16:04 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +
Function not meant to be called directly.

2024-01-26 18:10 UTC, randrescastaneda commented
> Hello - I have not done a full review, but made some comments. Please take a look, and let me know what you think. Thanks!
> 
> Some comments are about things that happen across the PR (I haven't highlighted every line of code were this happens), for instance the use of `cli` in low-level functions and referencing package with `package_name::function_name`

Hi @tonyfujs, regarding `cli` I think there is no cost including it and the gains in clarity are great. yet, we can remove them. I understand what you mean about low-level functions, but I think we should meet a middle ground, especially for conditions. I can compromise removing the `cli` calls, but I think the conditions in some of the functions should remain. 

Regarding referencing package, I'll make sure reference properly, but be aware some functions from `cli` and all the functions from `collapse` have been imported, so there is no need to reference them.  This is an important point. the `collapse` package brings a lot of benefits that can be gradually implemented in wbpip to speed up processes, that is why I imported the whole thing.

2024-01-26 18:10 UTC, randrescastaneda commented on DESCRIPTION
> +    PIP-technical-team/pipload@new_pipeline
Yes, this is an error. It should not be there. I'll make sure we remove it. 
Thanks.

2024-01-26 18:26 UTC, randrescastaneda commented on R/gd_compute_pip_stats_lb.R
> +  pov_gap <- gd_compute_pov_gap_lb( mean,  povline, headcount, A, B, C)
You're right, now the `pov_gap` and `severity` are flexible enough to either compute `u` inside or to receive `u` if it was computed previously. This second use is intended for `gd_compute_poverty_stats_lb` to gain some efficiency. The first use is intended for user be call by the user directly. Before, the user had to calculate `u` before she was able to get the `pov_gap` or `severity`. 

Bottom line, `u` should be passed to pov_gap and severity. 

We will take care of that.

2024-01-26 18:28 UTC, randrescastaneda commented on R/md_compute_bins.R
> +    return(dt[, bins])
I'll check. thanks.

2024-01-26 18:29 UTC, randrescastaneda commented on R/md_compute_poverty_stats.R
> +) {
Thanks. We'll do that.

2024-01-26 18:29 UTC, randrescastaneda commented on R/md_compute_poverty_stats.R
> +    weight_total      <- fsum(weight)
`collapse` is fully imported, so no need to reference the package.

2024-01-26 18:30 UTC, randrescastaneda commented on R/md_compute_poverty_stats.R
> +  povgap <- fsum(relative_distance * weight_pov) / weight_total
same as above

2024-01-29 17:53 UTC, randrescastaneda commented
Hi @tonyfujs, 

You can check the PR again. I removed all the informative `cli` messages that we introduced this round, but I left the ones that were already present in the package. All the tests are passing. Please, feel free to push back as much as needed.

Thanks. 


![image](https://github.com/PIP-Technical-Team/wbpip/assets/35301997/3554e64a-8658-4268-b459-40b332181491)

2024-02-16 13:36 UTC, tonyfujs requested changes
This looks good to me. I only added:
- One question
- One suggestion
- One request for change (replace `sapply` with `vapply`

Thanks!

2024-02-16 13:36 UTC, tonyfujs commented on R/md_compute_poverty_stats.R
> +  }
Why is this necessary?

2024-02-16 13:36 UTC, tonyfujs commented on R/md_infer_poverty_line.R
>    }
`sapply` should be replace by `vapply` because `vapply` never fails silently. `sapply` is more for interactive use. Within functions, `vapply` is much more robust.

2024-02-16 18:39 UTC, randrescastaneda commented
Hi @tonyfujs , 

this PR is ready. All checks pass

![image](https://github.com/PIP-Technical-Team/wbpip/assets/35301997/1842407a-ac03-4056-a7b1-2d90b8fec026)

2024-02-21 00:48 UTC, merged