Dev stage2 into DEV
PIP-Technical-Team/wbpip pull request #254
Opened 2024-04-02 02:03 UTC by zander-prinsloo

1. Key values: removed as individual arguments, instead supplied as one list using argument `key_values` created using `gd_lq_key_values`
2. Remove unnecessary `dd` argument from `gd_compute_mld_*` and `gd_compute_watts_*`
3. This is potentially too much information, but here it is. The function `check_curve_validity_lq()` is called in `DEV` in the following ways. It is used a) line 115 in gd_compute_dist_stats.R in `gd_estimate_dist_stats_lq()`, where the r argument is squared as the input; b) line 784 in gd_compute_pip_stats_lq.R in `gd_estimate_lq()` where the r argument is not squared; c) in line 137 of gd_compute_poverty_stats.R in function `gd_estimate_poverty_stats_lq()` where the r argument is not squared; d) line 103  of prod_gd_compute_pip_stats_lq().R in function `prod_gd_estimate_lq()` where the r argument is not squared. Therefore, out of the four times it is called it is only the first where the r argument is squared. The paper (Villasenor & Arnold, 1989) uses the square root for the `r` argument, similar (although with a denominator) to `r` calculated in `gd_lq_key_values`. However, the other three calls of `check_curve_validity_lq()` mentioned above do not calculate the square root for r prior to the function call , which is why they just use the `r` argument directly. What has been done here is to i) use the square root for `r` in `key_values` list; ii) but then square the `r` argument within `check_curve_validity_lq()`. However, `r` is never actually used anywhere in `check_curve_validity_lq()` except in `if(r 0) {return(...)}` as an early check. This requires a bit more investigation to see whether the `r` argument is necessary here. 
4. 

Exported many additional functions.
Some functions have been improved/vectorized. The new functions have taken the names of the old functions, and the old functions have the prefix "old_"

2024-04-04 22:51 UTC, randrescastaneda approved these changes
Hi @tonyfujs, 

All changes are approved. I added small modifications here and there that do not affect in any substantial sense the main contributions of the PR. 

All checks pass
![image](https://github.com/PIP-Technical-Team/wbpip/assets/35301997/7ccfa852-84ff-410c-b800-b8c4d359d281)

2024-05-14 22:20 UTC, randrescastaneda commented
Hi @tonyfujs , 

In this PR we have made several improvements to the efficiency of wbpip. In general, we are working towards vectorizing most of the functions, so that the API could also be vectorized, specially in the poverty line. To achieve that, we need to have the `wbpip` base working first. Could you please take a look and merge if ready? Thanks.  

![image](https://github.com/PIP-Technical-Team/wbpip/assets/35301997/d0e80294-4bb5-41e7-b91c-0a2b1da4530b)

2024-05-31 09:00 UTC, tonyfujs requested changes
Hi @zander-prinsloo - I'm getting an error when running `devtools::check()`
![image](https://github.com/PIP-Technical-Team/wbpip/assets/1552634/c5011638-a643-4e49-be5f-f434deeae7cc)

Can you please review? Thanks!

2024-05-31 14:16 UTC, zander-prinsloo commented on R/md_compute_poverty_stats.R
> +#' dt_fgt <- data.frame(povline = fgt$povline,
@tonyfujs I made the change, and re-documented. 

There is now no error when I run `devtools::check()` (see below) 

![image](https://github.com/PIP-Technical-Team/wbpip/assets/62433917/57fa5d84-2c1f-4c2b-bed3-cd62855eed90)

2024-05-31 15:56 UTC, tonyfujs commented
Thanks @zander-prinsloo Everything looks good for me too now. The only other thing that I think we should do now, is remove all the old functionsas they are no longer needed

2024-06-03 05:29 UTC, shahronak47 commented on NAMESPACE
> -export(gd_compute_fit_lq)
Hi @zander-prinsloo , sorry to jump in but I am using `dev_stage2` for one of my task and I noticed that function `gd_compute_fit_lq` is no longer exported whereas `gd_compute_fit_lb` is exported which seems a bit odd to me. Is this intentional or has happened by mistake? 

cc : @randrescastaneda @tonyfujs

2024-06-03 19:30 UTC, zander-prinsloo commented on NAMESPACE
> -export(gd_compute_fit_lq)
@shahronak47 Thank you. The function `gd_compute_fit_lq()` has now been exported.

2024-06-04 01:50 UTC, zander-prinsloo commented
> Thanks @zander-prinsloo Everything looks good for me too now. The only other thing that I think we should do now, is remove all the old functionsas they are no longer needed

@tonyfujs most recent commit removes all old functions with prefix "old_". The tests are also adjusted to account for their removal. CC @randrescastaneda

2024-06-13 05:00 UTC, zander-prinsloo commented
Last changes were to increase efficiency in `md_compute_polarization` and correct the tests. The benchmarks in the tests were slightly off (at around the fourth decimal). When using the formula to calculate the benchmarks analytically, the tests pass. 

Ready to review @tonyfujs @randrescastaneda 

All checks passing
![image](https://github.com/PIP-Technical-Team/wbpip/assets/62433917/ca9d4545-fd3f-48e1-957e-458e6e89c1ac)

2024-06-20 23:13 UTC, randrescastaneda approved these changes

2024-06-21 05:37 UTC, tonyfujs commented
Great. Approved!

2024-06-21 05:42 UTC, tonyfujs approved these changes

2024-06-21 13:01 UTC, merged